### ISSUE TITLE
`colormode` does not work

### ISSUE THREAD

**Issue by BaumiCoder** [se2p/se2thesis#16]
In the [documentation](http://mirrors.ctan.org/macros/latex/contrib/se2thesis/se2thesis.pdf) at *3.1 Load-time options* the `colormode` is documented as:
> Select the color scheme used by the automatically loaded se2colors package, see Section 4 for a description.

In Section 4 there are several options listed for `cmode` in table 1. I would understand, that this option should also be valid for the `colormode` class option, but using options from there like `BW`, `bw` or `RGB` leads to the error message `Key 'seiithesis/colormode' accepts only a fixed set of choices.`. Although, `rgb` works as an option.

Do I misunderstand something of the documentation or is that a bug in the class?

**Comment by stephanlukasczyk** [comment]
Not sure, which version you were referring to, but it's true that `se2thesis` did not expose all possible values from `se2colors` to the user.  The relevant `se2thesis` code: https://github.com/se2p/se2thesis/blob/a080f9838d859f94ab4334604dba8355ef22d80b/se2thesis.dtx#L791-L794 and the related `se2colors` code: https://github.com/se2p/se2thesis/blob/a080f9838d859f94ab4334604dba8355ef22d80b/se2colors.dtx#L243-L271

However, I've just pushed a fixing release [here](https://github.com/se2p/se2thesis/releases/tag/v4.0.3) and also uploaded it to CTAN, where it will take usually one or two days until it will be available from the various mirror servers.

**Comment by BaumiCoder** [comment]
I had the version 3.4.0 and after an update I got 4.0.3. With the new version it works as documented.
Thank you for the fast bugfix :+1:
