### ISSUE TITLE
Referencing to resq environment with \cref does not work 

### ISSUE THREAD

**Issue by BaumiCoder** [se2p/se2thesis#8]
I encountered, that it is not possible to use `\cref` for the `resq` environment. It would be nice if that is supported. I also figured out some workaround (see example project), maybe they could be an inspiration for a possible solution / implementation in se2thesis.

Example project:
 - Code: https://code.it-baumi.de/BaumiCoder/se2thesis_test
 - PDF Release: https://code.it-baumi.de/BaumiCoder/se2thesis_test/releases/tag/v1

**Comment by stephanlukasczyk** [comment]
While your solution might work, the documentation of the `cleveref` package clearly states the generic solution for the package, which #11 now adds to `se2thesis`.  I have some more things to implement, thus it is not yet ready for a release, but you can download the sources and build it your own, using `l3build install` to install it to your local TEXMF tree.
